// Builds screens.mjs, the suite's screen part: public/app/chat.mjs with chat.css carried inside it, since the
// suite serves one screens file and loads the kit itself. --check fails if screens.mjs is out of date.
import fs from 'node:fs';
import { scopeCss } from './scope-css.mjs';

// Scoped to .chat-root (the element the suite mounts Chat into), so nothing reaches the suite's shell.
const css = scopeCss(fs.readFileSync('public/app/chat.css', 'utf8'), '.chat-root');
const js = fs.readFileSync('public/app/chat.mjs', 'utf8');
const out = `// GENERATED by scripts/build-screens.mjs from public/app/chat.mjs and chat.css. Do not edit by hand.\nconst CHAT_CSS = ${JSON.stringify(css)};\n${js}`;
if (process.argv.includes('--check')) {
  if (!fs.existsSync('screens.mjs') || fs.readFileSync('screens.mjs', 'utf8') !== out) { console.error('screens.mjs is out of date: run npm run build:screens'); process.exit(1); }
  console.log('screens.mjs is current');
} else {
  fs.writeFileSync('screens.mjs', out);
  console.log(`wrote screens.mjs (${Math.round(out.length / 1024)} KB)`);
}
